### PR TITLE
My branch

### PR DESCRIPTION
**Pull request by ntzwilly**
## Project requirements

- Create a new empty repo.
- Copy your code from the project that you completed during the Admissions Trial
- Create a new branch for your copied code.
- Open a pull request.
- Play the role of the Code Reviewer:
- Follow the list from the article "How to give a code review?".
- Check if you have used semantic HTML tags.
- Check if you applied HTML & CSS best practices.
- Add as many comments as possible in the given time and finish your review. Remember to add a minimum of 2 comments - - -you will definitely find something that could have been done better!
- Copy a link to the pull request and ask for a code review in your Student Dashboard as usual. (The only difference will be that the Code Reviewer won't check your code but the review you performed - isn't it a code review inception? ;))

### CODE REVIEW

**Review by Spayco — CHANGES_REQUESTED** [review]
Hi @hiromataba, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️

- please find at least 2 issues and comment on them using GitHub features, double-check the lesson so you understand more

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by ntzwilly — COMMENTED** [review]
Changes required :recycle: 

Please check my comments and make the required changes.

Submit for a re-review when you are done.

Thanks

**Comment by ntzwilly** [comment]
Hi Spayco,

Thank you for your feedback. I have added my comments.

Best,
Willy

**Review by christianotieno — APPROVED** [review]
Hi @ntzwilly , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
